### ISSUE TITLE
Press-level meta tags

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/path#3]
**User Story**
As someone searching for or sharing a link to this website, I'd like for a title, image, and description to load in the search engine or social media app I'm using.

**Proposed solution**
- [x] Add press-level meta tags for title, image, and description.
- [x] Debug image display
- [x] Test on olhbeta
